version: '2'

services:
  syslog:
    build: ./syslog-ng
    volumes:
      - ./syslog-ng/conf/syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf
      - ./syslog-ng/bin/send_syslog.py:/usr/local/bin/send_syslog.py

  hadoop:
    image: sequenceiq/hadoop-docker:2.7.1
